/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asking;

import javax.swing.JOptionPane;

/**
 *
 * @author UNI
 */
public class jasking extends javax.swing.JFrame {

    /**
     * Creates new form jasking
     */
    public jasking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        diagnosa = new javax.swing.JButton();
        bersih = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        penyakit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        solusi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catatan = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        tdd2 = new javax.swing.JRadioButton();
        tdd3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        g1 = new javax.swing.JCheckBox();
        g2 = new javax.swing.JCheckBox();
        g3 = new javax.swing.JCheckBox();
        g4 = new javax.swing.JCheckBox();
        g5 = new javax.swing.JCheckBox();
        g7 = new javax.swing.JCheckBox();
        g8 = new javax.swing.JCheckBox();
        g6 = new javax.swing.JCheckBox();
        g9 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        tds1 = new javax.swing.JRadioButton();
        tds2 = new javax.swing.JRadioButton();
        tds3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        tdd1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel1.setText("DECISION SUPPORT SYSTEM APPLICATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        diagnosa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        diagnosa.setText("DIAGNOSA");
        diagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosaActionPerformed(evt);
            }
        });

        bersih.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bersih.setText("BERSIHKAN");
        bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihActionPerformed(evt);
            }
        });

        keluar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("HASIL DIAGNOSA");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("PENYAKIT");

        penyakit.setEditable(false);
        penyakit.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("SOLUSI");

        solusi.setEditable(false);
        solusi.setBackground(new java.awt.Color(204, 204, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("KETERANGAN");

        catatan.setBackground(new java.awt.Color(204, 204, 255));
        catatan.setColumns(20);
        catatan.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        catatan.setRows(5);
        jScrollPane1.setViewportView(catatan);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        tdd2.setBackground(new java.awt.Color(255, 255, 255));
        tdd2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tdd2.setText("II");

        tdd3.setBackground(new java.awt.Color(255, 255, 255));
        tdd3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tdd3.setText("III");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("PLIH GEJALA");

        g1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g1.setText("G1");

        g2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g2.setText("G2");

        g3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g3.setText("G3");

        g4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g4.setText("G4");

        g5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g5.setText("G5");

        g7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g7.setText("G7");

        g8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g8.setText("G8");

        g6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g6.setText("G6");

        g9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g9.setText("G9");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tekanan Darah Sistolik");

        tds1.setBackground(new java.awt.Color(255, 255, 255));
        tds1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tds1.setText("I");
        tds1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tds1ActionPerformed(evt);
            }
        });

        tds2.setBackground(new java.awt.Color(255, 255, 255));
        tds2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tds2.setText("II");

        tds3.setBackground(new java.awt.Color(255, 255, 255));
        tds3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tds3.setText("III");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tekanan Darah Diastolik");

        tdd1.setBackground(new java.awt.Color(255, 255, 255));
        tdd1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tdd1.setText("I");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("PILIH KODE TEKANAN DARAH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(g9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(g3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(g4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(g1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(g2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(g7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(g8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(g5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(g6))
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tds1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tds2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tds3))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tdd1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tdd2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tdd3)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g1)
                    .addComponent(g2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g3)
                    .addComponent(g4)
                    .addComponent(tds1)
                    .addComponent(tds2)
                    .addComponent(tds3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g5)
                    .addComponent(g6)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g7)
                    .addComponent(g8)
                    .addComponent(tdd1)
                    .addComponent(tdd2)
                    .addComponent(tdd3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(g9)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("NAMA PASIEN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ishak M");

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("12181653");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 8)); // NOI18N
        jLabel13.setText("*Note Gejala");

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 8)); // NOI18N
        jLabel14.setText("K1. G1 + G2 + G3");

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 8)); // NOI18N
        jLabel15.setText("K2. G2 + G4");

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 8)); // NOI18N
        jLabel16.setText("K3. G4 + G7 + G9");

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 8)); // NOI18N
        jLabel17.setText("K4. G8 + G9");

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 8)); // NOI18N
        jLabel18.setText("K5. G1 +G4 + G5");

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 0, 8)); // NOI18N
        jLabel19.setText("K6. G5 + G7");

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 0, 8)); // NOI18N
        jLabel20.setText("K7. G2 + G3 + G7");

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 0, 8)); // NOI18N
        jLabel21.setText("K8. G5 + G8 + G9");

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 0, 8)); // NOI18N
        jLabel22.setText("K9. G1 + G4");

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 0, 8)); // NOI18N
        jLabel23.setText("K10. G4 + G6");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nama))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(diagnosa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bersih, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(keluar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(23, 23, 23)
                                .addComponent(solusi, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(penyakit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel9))
                                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(diagnosa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(bersih, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(solusi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(penyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tds1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tds1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tds1ActionPerformed

    private void diagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosaActionPerformed
       boolean k1 = tds1.isSelected()&&tdd1.isSelected()&&g1.isSelected()&& g2.isSelected()&&g3.isSelected();
       boolean k2 = tds2.isSelected()&&tdd3.isSelected()&&g2.isSelected()&&g4.isSelected();
       boolean k3 = tds1.isSelected()&&tdd3.isSelected()&&g4.isSelected()&&g7.isSelected()&&g9.isSelected();
       boolean k4 = tds2.isSelected()&&tdd2.isSelected()&&g8.isSelected()&&g9.isSelected();
       boolean k5 = tds2.isSelected()&&tdd1.isSelected()&&g1.isSelected()&&g4.isSelected()&&g5.isSelected();
       boolean k6 = tds3.isSelected()&&tdd2.isSelected()&&g5.isSelected()&&g7.isSelected();
       boolean k7 = tds3.isSelected()&&tdd1.isSelected()&&g2.isSelected()&&g3.isSelected()&&g7.isSelected();
       boolean k8 = tds2.isSelected()&&tdd2.isSelected()&&g5.isSelected()&&g8.isSelected()&&g9.isSelected();
       boolean k9 = tds1.isSelected()&&tdd2.isSelected()&&g1.isSelected()&&g4.isSelected();
       boolean k10 = tds1.isSelected()&&tdd2.isSelected()&&g4.isSelected()&&g6.isSelected();
       String name = nama.getText();
       if (k1) {
            String kodesakit = "A";
            String kodesolusi = "S1";
            String kodecatat ="Nama : "+name+ "\n Kasus : K1 \n---------------\n TDS lebih rendah dari 100mmHg \n TDD lebih rendah dari 80mmHg";
            penyakit.setText(kodesakit);
            solusi.setText(kodesolusi);
            catatan.setText(kodecatat);
        } else if(k2){
            String kodesakit = "B";
            String kodesolusi = "S2";
            String kodecatat ="Nama : "+name+ "\n Kasus : K2 \n---------------\n TDS sama dengan atau lebih rendah dari\n 100mmHg dan lebih rendah dari 120mmHg \n------------------------------\n TDD lebih tinggi dari 100mmHg";
            penyakit.setText(kodesakit);
            solusi.setText(kodesolusi);
            catatan.setText(kodecatat);
        }else if(k3){
            String kodesakit = "C";
            String kodesolusi = "S3";
            String kodecatat ="Nama : "+name+ "\n Kasus : K3 \n---------------\n TDS lebih rendah dari 100mmHg \n------------------------------\n TDD sama dengan atau lebih tinggi\n dari 100mmHg";
            penyakit.setText(kodesakit);
            solusi.setText(kodesolusi);
            catatan.setText(kodecatat);
        } else if(k4){
            String kodesakit = "D";
            String kodesolusi = "S4";
            String kodecatat ="Nama : "+name+ "\n Kasus : K4 \n---------------\n TDS sama dengan atau lebih rendah\n dari 100mmHg\n------------------------------\n TDD lebih rendah dari 120mmHg \n TDD sama dengan atau lebih rendah dari 800mmHg dan lebih rendah dari 100mmHg";
            penyakit.setText(kodesakit);
            solusi.setText(kodesolusi);
            catatan.setText(kodecatat);
        } else if(k5){
            String kodesakit = "A";
            String kodesolusi = "S5";
            String kodecatat ="Nama : "+name+ "\n Kasus : K5 \n---------------\n TDS sama dengan atau lebih rendah dari 100mmHg\n dan lebih rendah dari 120mmHg\n------------------------------\n TDD lebih rendah dari 80mmHg";
            penyakit.setText(kodesakit);
            solusi.setText(kodesolusi);
            catatan.setText(kodecatat);
        } else if(k6){
            String kodesakit = "C";
            String kodesolusi = "S6";
            String kodecatat ="Nama : "+name+ "\n Kasus : K6 \n---------------\n TDS sama dengan atau lebih tinggi dari 120mmHg\n------------------------------\n TDD sama dengan atau lebih rendah dari 80mmHg dan\n lebih rendah dari 100mmHg";
            penyakit.setText(kodesakit);
            solusi.setText(kodesolusi);
            catatan.setText(kodecatat); 
        } else if(k7){
            String kodesakit = "A";
            String kodesolusi = "S5";
            String kodecatat ="Nama : "+name+ "\n Kasus : K7 \n---------------\n TDS sama dengan atau lebih tinggi dari 120mmHg \n------------------------------\n TDD lebih rendah dari 80mmHg";
            penyakit.setText(kodesakit);
            solusi.setText(kodesolusi);
            catatan.setText(kodecatat); 
        } else if(k8){
            String kodesakit = "C";
            String kodesolusi = "S8";
            String kodecatat ="Nama : "+name+ "\n Kasus : K8 \n---------------\n TDS sama dengan atau lebih rendah dari 100mmHg dan\n lebih rendah dari 120mmHg \n------------------------------\n TDD sama dengan atau lebih rendah dari 80mmHg dan\n lebih rendah dari 100mmHg";
            penyakit.setText(kodesakit);
            solusi.setText(kodesolusi);
            catatan.setText(kodecatat); 
        } else if(k9){
            String kodesakit = "A";
            String kodesolusi = "S1";
            String kodecatat ="Nama : "+name+ "\n Kasus : K9 \n---------------\n TDS lebih rendah dari 100mmHg \n------------------------------\n TDD sama dengan atau lebih rendah dari 80mmHg dan\n lebih rendah dari 100mmHg";
            penyakit.setText(kodesakit);
            solusi.setText(kodesolusi);
            catatan.setText(kodecatat); 
        } else if(k10){
            String kodesakit = "B";
            String kodesolusi = "S8";
            String kodecatat ="Nama : "+name+ "\n Kasus : K8 \n---------------\n TDS lebih rendah dari 100mmHg \n------------------------------\n TDD sama dengan atau lebih rendah dari 80mmHg dan\n lebih rendah dari 100mmHg";
            penyakit.setText(kodesakit);
            solusi.setText(kodesolusi);
            catatan.setText(kodecatat); 
        } else {
            String kodesakit = "null";
            String kodesolusi = "null";
            String kodecatat ="Nama : "+name+ "\n---------------\n Gejala yang Anda rasakan belum dapat\n di Diagnosa oleh sistem kami";
            penyakit.setText(kodesakit);
            solusi.setText(kodesolusi);
            catatan.setText(kodecatat); 
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_diagnosaActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        char box = (char) JOptionPane.showConfirmDialog(null, "Diagnosa lagi?","Sistem Pendukung Keputusan",JOptionPane.YES_NO_OPTION);
        if (box == (char) JOptionPane.YES_OPTION) {
    g1.setSelected(false);
    g2.setSelected(false);
    g3.setSelected(false);
    g4.setSelected(false);
    g5.setSelected(false);
    g6.setSelected(false);
    g7.setSelected(false);
    g8.setSelected(false);
    g9.setSelected(false);
    tds1.setSelected(false);
    tds2.setSelected(false);
    tds3.setSelected(false);
    tdd1.setSelected(false);
    tdd2.setSelected(false);
    tdd3.setSelected(false);
    this.penyakit.setText("");
    this.solusi.setText("");
    this.catatan.setText("");
        }else if (box == (char) JOptionPane.NO_OPTION) {
        System.exit(0);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihActionPerformed
    g1.setSelected(false);
    g2.setSelected(false);
    g3.setSelected(false);
    g4.setSelected(false);
    g5.setSelected(false);
    g6.setSelected(false);
    g7.setSelected(false);
    g8.setSelected(false);
    g9.setSelected(false);
    tds1.setSelected(false);
    tds2.setSelected(false);
    tds3.setSelected(false);
    tdd1.setSelected(false);
    tdd2.setSelected(false);
    tdd3.setSelected(false);
    penyakit.setText("");
    solusi.setText("");
    catatan.setText("");
    nama.setText("");
    }//GEN-LAST:event_bersihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jasking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jasking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jasking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jasking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jasking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bersih;
    private javax.swing.JTextArea catatan;
    private javax.swing.JButton diagnosa;
    private javax.swing.JCheckBox g1;
    private javax.swing.JCheckBox g2;
    private javax.swing.JCheckBox g3;
    private javax.swing.JCheckBox g4;
    private javax.swing.JCheckBox g5;
    private javax.swing.JCheckBox g6;
    private javax.swing.JCheckBox g7;
    private javax.swing.JCheckBox g8;
    private javax.swing.JCheckBox g9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField penyakit;
    private javax.swing.JTextField solusi;
    private javax.swing.JRadioButton tdd1;
    private javax.swing.JRadioButton tdd2;
    private javax.swing.JRadioButton tdd3;
    private javax.swing.JRadioButton tds1;
    private javax.swing.JRadioButton tds2;
    private javax.swing.JRadioButton tds3;
    // End of variables declaration//GEN-END:variables
}
